### ISSUE TITLE
[Issue] Toggle-Dark-Light doesn't update some UI / explorer stuff + Icon lost on explorer crash.

### ISSUE THREAD

**Issue by zhmstr** [danielgjackson/toggle-dark-light#1]
If changing with tray icon, it causes some UI inconsistencies, some apps running might have dropdown with the old theme (it stays in white after switching to dark) and even some elements mismatch..

**From this:**
![image](https://github.com/danielgjackson/toggle-dark-light/assets/107897693/491e80d6-436c-449c-9793-a2401e36ead4)
**To this:**
![image](https://github.com/danielgjackson/toggle-dark-light/assets/107897693/3d9552f0-7cee-4b4d-9a61-0c2f61d1984c)

You can notice that the task manager window title header is duped and mismatched.
If you change using Windows 11 Config GUI, it won't cause any of those troubles. And no, it's not the StartAllBack.

I guess this info would be relevant for you to fix that: [win32-darkmode](https://github.com/ysc3839/win32-darkmode), [article](https://itecnote.com/tecnote/windows-win10-dark-theme-how-to-use-in-winapi/)

Windows 11 - 22H2 [Build 22621.2428]

**Comment by danielgjackson** [comment]
Hi @ZhMster -- thanks for the bug report, apologies for the late response.

I'd noticed this issue too, but wasn't certain how to fix it.  

Using the *Spy++* tool, I saw that `explorer.exe` was receiving a `WM_SETTINGSCHANGE` notification when changing the settings through the UI, and a bit of searching lead to this likely being sent with an `ImmersiveColorSet` string.  In fact, this message is handled in the `win32-darkmode` project you'd sent a link to, but I hadn't noticed that detail before.

I've made this fix in the latest version:

*  [Releases](https://github.com/danielgjackson/toggle-dark-light/releases)

...and it all seems to work well for me now (although it takes an extra second or so for *File Explorer* windows to settle down). 

**Edit:** Occasionally, I have seen the main area of *File Explorer* not refresh correctly, but this is fixed e.g. by navigating away and back again -- and I think I've seen the same behaviour when changing through the Settings screen...

Let me know if you spot any other issues, and I'll see what I can do.  Cheers!
